### PR TITLE
update to Play 2.6.5

### PR DESCRIPTION
**Pull request by agebhar1**

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
👍

**Comment by OlegIlyenko** [comment]
Just released in https://github.com/sangria-graphql/sangria-play-json/releases/tag/v1.0.4

**Comment by OlegIlyenko** [comment]
Play is quite hard to keep up with, it is already v2.6.6 :) I used this version + this already includes the test you added in https://github.com/sangria-graphql/sangria-marshalling-testkit/pull/1

**Comment by agebhar1** [comment]
Thanks @OlegIlyenko! I got it. Play Framework's latest release is 2.6.5 but Play Json's is 2.6.6 - D'oh!

**Comment by OlegIlyenko** [comment]
Maybe it was just a small bugfix or somethings like this so that v2.6.5 and v2.6.5 are still binary compatible?

**Comment by agebhar1** [comment]
Yes @OlegIlyenko , both are binary compatible:

```
$ japi-compliance-checker play-json_2.12-2.6.5.jar play-json_2.12-2.6.6.jar
Preparing, please wait ...
Using Java 1.8.0_141
Reading classes 2.12-2.6.5 ...
Reading classes 2.12-2.6.6 ...
Comparing classes ...
Creating compatibility report ...
Binary compatibility: 100%
Source compatibility: 100%
Total binary compatibility problems: 0, warnings: 0
Total source compatibility problems: 0, warnings: 0
Report: compat_reports/play-json/2.12-2.6.5_to_2.12-2.6.6/compat_report.html
```

**Pull request merged**
