### PR TITLE
Cross-compile for play 2.8, 2.9 and 3.0

### LINKED ISSUE #238: Add support for play-json 2.9 & 3.0
play (and play-json) 2.9.0 and 3.0.0 were released a few weeks back, as can be seen here:

https://github.com/playframework/playframework/releases/tag/2.9.0
https://github.com/playframework/playframework/releases/tag/3.0.0

It would be great if this project could publish a compatible release built on top of it!

### PR DESCRIPTION
**Pull request by tarmath**
Fixes #238

### CODE REVIEW

**Comment by tarmath** [comment]
@sh0hei 🙏🏻

**Comment by tarmath** [comment]
@sh0hei fixed... 🤞

**Comment by tarmath** [comment]
@sh0hei okay, made githubWorkflowCheck task happy!

I have to apologize for the many tries. 
Github workflows are brand new to me, and I had no idea these extra commands were running during builds.

**Review by sh0hei — APPROVED** [review]
Thanks a lot, @tarmath !

**Pull request merged**
